-- ============================================
-- SCRIPT DE MIGRACIÓN: CUENTA CORRIENTE
-- ============================================
-- Este script crea la tabla debt_transactions
-- Ejecutar en Supabase SQL Editor
-- ============================================

-- Crear tabla de transacciones de deuda
CREATE TABLE IF NOT EXISTS public.debt_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  client_id bigint REFERENCES public.users(id) ON DELETE CASCADE,
  client_name text,              -- Nombre del cliente (denormalizado)
  amount numeric DEFAULT 0.0,    -- Importe de la transacción
  transaction_type text NOT NULL CHECK (transaction_type IN ('charge', 'payment')), -- 'charge' o 'payment'
  balance_after numeric DEFAULT 0.0, -- Balance después de la transacción
  date timestamp DEFAULT timezone('utc'::text, now()), -- Fecha de la transacción
  notes text                     -- Notas opcionales
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.debt_transactions ENABLE ROW LEVEL SECURITY;

-- Crear política para permitir todas las operaciones
CREATE POLICY "Enable flow for anon" ON public.debt_transactions FOR ALL USING (true);

-- Crear índices para mejorar performance
CREATE INDEX IF NOT EXISTS idx_debt_transactions_client_id ON public.debt_transactions(client_id);
CREATE INDEX IF NOT EXISTS idx_debt_transactions_date ON public.debt_transactions(date DESC);
CREATE INDEX IF NOT EXISTS idx_debt_transactions_type ON public.debt_transactions(transaction_type);

-- Verificar que la tabla se creó correctamente
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_name = 'debt_transactions'
ORDER BY ordinal_position;
