
-- Clean up old and new tables with CASCADE to handle dependencies
drop table if exists public.transactions cascade;
drop table if exists public.sales cascade;
drop table if exists public.expenses cascade;
drop table if exists public.users cascade;

-- 1. USERS TABLE (Clientes) - Kept from previous step as requested for Customer DB
create table public.users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_id text,                 -- ClienteID
  name text,                      -- Nombre
  last_load_date text,            -- Fecha de Ultima carga
  observations text,              -- Observaciones
  phone text unique,              -- Telefono
  user_password text,             -- UsuarioContraseña
  user_view boolean default true, -- UsuarioVer
  user_photo text,                -- UsuarioFoto
  user_profile text default 'CLIENT', -- UsuarioPerfil
  user_status boolean default true,   -- UsuarioStatus
  coin_balance bigint default 0,  -- Cantidad de Monedas
  image_url text,                 -- Imagen
  debt_balance numeric default 0.0 -- Cta Cte
);

-- 2. SALES TABLE (Ventas/Ingresos)
create table public.sales (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  legacy_id text,              -- IDingreso (for import)
  date timestamp,              -- Fecha
  observations text,           -- Observaciones
  amount numeric default 0.0,  -- Importe
  branch text,                 -- sucursal (Rawson / Rivadavia)
  month_number integer         -- mes nro
);

-- 3. EXPENSES TABLE (Egresos)
create table public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  legacy_id text,              -- IDEgreso (for import)
  date timestamp,              -- Fecha
  category text,               -- Categoria
  amount numeric default 0.0,  -- Importe
  observations text,           -- Observaciones
  branch text                  -- Sucursal
);

-- 4. COIN TRANSACTIONS TABLE (Transacciones de Vyper Coins)
create table public.coin_transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  client_id bigint references public.users(id) on delete cascade,
  client_name text,            -- Nombre del cliente (denormalizado para facilidad)
  amount numeric default 0.0,  -- Importe de la compra
  coins_added integer default 0, -- Cantidad de coins agregados
  date timestamp default timezone('utc'::text, now()) -- Fecha de la transacción
);


-- 5. DEBT TRANSACTIONS TABLE (Transacciones de Cuenta Corriente/Deuda)
create table public.debt_transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  client_id bigint references public.users(id) on delete cascade,
  client_name text,              -- Nombre del cliente (denormalizado)
  amount numeric default 0.0,    -- Importe de la transacción
  transaction_type text not null, -- 'charge' (compra en cuenta corriente) o 'payment' (pago)
  balance_after numeric default 0.0, -- Balance después de la transacción
  date timestamp default timezone('utc'::text, now()), -- Fecha de la transacción
  notes text                     -- Notas opcionales
);


-- RLS Policies
alter table public.users enable row level security;
alter table public.sales enable row level security;
alter table public.expenses enable row level security;
alter table public.coin_transactions enable row level security;
alter table public.debt_transactions enable row level security;

create policy "Enable flow for anon" on public.users for all using (true);
create policy "Enable flow for anon" on public.sales for all using (true);
create policy "Enable flow for anon" on public.expenses for all using (true);
create policy "Enable flow for anon" on public.coin_transactions for all using (true);
create policy "Enable flow for anon" on public.debt_transactions for all using (true);
